"""empty message

Revision ID: a131d0d4d5a8
Revises: a815ccc05edb
Create Date: 2021-03-13 18:39:01.410146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a131d0d4d5a8'
down_revision = 'a815ccc05edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('show_id', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'show_id')
    # ### end Alembic commands ###
